DROP TABLE IF EXISTS INCUBATEUR;

CREATE SEQUENCE "INCUBATEUR_SEQ"
    MINVALUE 1
    MAXVALUE 99999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE INCUBATEUR (
     id INT NOT NULL DEFAULT nextval('INCUBATEUR_SEQ') PRIMARY KEY,
     oeuf BOOLEAN NOT NULL,
     temps DOUBLE PRECISION NOT NULL
);