DROP TABLE IF EXISTS INVENTAIRE;

CREATE TABLE INVENTAIRE (
    type VARCHAR(63) PRIMARY KEY,
    quantity BIGINT NOT NULL
);

DROP TABLE IF EXISTS EQUIPE;

CREATE TABLE EQUIPE (
    id BIGINT PRIMARY KEY,
    nom VARCHAR(63) NOT NULL
);