version: "3"
services:

  # API GATEWAY
  gateway:
    build:
      context: "./API_GATEWAY"
    ports:
      - "8080:8080"

  # BOUTIQUE
  boutique:
    build:
      context: "./Boutique"
    ports:
      - "8081:8081"

  # CAVE
  cave:
    build:
      context: "./Cave"
    ports:
      - "8082:8082"

  # COFFRE
  coffre:
    build:
      context: "./Coffre"
    ports:
      - "8083:8083"

  # COMBAT
  combat:
    build:
      context: "./Combat"
    ports:
      - "8084:8084"

  # JOUEUR
  joueur:
    build:
      context: "./Joueur"
    ports:
      - "8085:8085"

  # MONSTRE
  monstre:
    build:
      context: "./Monstre"
    ports:
      - "8086:8086"

  # LOG
  log:
    build:
      context: "./Log"
    ports:
      - "8087:8087"
