DROP TABLE IF EXISTS BOUTIQUE;

CREATE SEQUENCE "BOUTIQUE_SEQ"
    MINVALUE 1
    MAXVALUE 99999
    INCREMENT BY 1
    START WITH 1
    NOCACHE
    NOCYCLE;

CREATE TABLE BOUTIQUE (
     nom VARCHAR(64) NOT NULL PRIMARY KEY,
     price INT NOT NULL,
     quantity INT NOT NULL,
);